name: Generate Datas

on:
  schedule: # execute every 5 hours
    - cron: "* */5 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
    
      # Check repo under $GITHUB_WORKSHOP, se your job can access it
      - uses: actions/checkout@v2
      
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Lucasdiogo6
          git_out_path: dist/github-contribution-grid-snake.git
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - run: git status

      - name: Push changes
        uses: ad-t/github-push-action@master
        with: 
          github_token: $(( secrets.GITHUB_TOKEN ))
          branch: master
          force: true
        
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
